### ISSUE TITLE
App is doesn't working correct

### ISSUE THREAD

**Issue by trustill** [Gerutro/TempCleaner#1]
**Describe the bug**
App is doesn't works, the console closes immediately. 

**To Reproduce**
1. Run app
2. Console is opens, but the basic functions don't work.

**Expected behavior**
When you start the program, information about cleaning should be entered in the console.

**.log file**
https://github.com/user-attachments/files/15959933/main.log

**Desktop (please complete the following information):**
 - Windows
 - 10
 - 1.2.0-rx0

**Comment by Gerutro** [comment]
Fixed in V. 1.2.1-RX0
